### PR TITLE
Replaced depreciated Chef::REST with Chef::ServerAPI

### PR DESCRIPTION
**Pull request by e100**
> Upgraded ChefDK and now knife encrypted attribute give me an error.
> Chef Development Kit Version: 0.15.15
> chef-client version: 12.11.18
> 
> Line 378 /lib/chef/encrypted_attribute/search_helper.rb is the problem.
> 
> Chef::REST is depreciated, simply replacing it with Chef::ServerAPI resolved the error.

### CODE REVIEW

**Comment by zuazo** [comment]
Hi @e100,

Thanks for the PR.

Do you know if this breaks backward compatibility? I'm OK with that. But if that's the case, the requirements in the README will need to be updated.

**Comment by e100** [comment]
Chef::ServerAPI has been around for a few years so I think its in 11 too but I don't know for sure.

**Comment by zuazo** [comment]
OK, I tested this manually with Chef version `11.4.0` and fails. This PR will require at least Chef version `11.8.0`.

So, two small requests:

- Could you please fix the RuboCop offenses?

```
$ rake style
Running RuboCop...
Inspecting 72 files
..........................C.............................................

Offenses:

spec/unit/encrypted_attribute/search_helper.rb:428:81: C: Line is too long. [81/80]
        allow_any_instance_of(Chef::ServerAPI).to receive(:post_rest).and_return(
                                                                                ^
spec/unit/encrypted_attribute/search_helper.rb:445:81: C: Line is too long. [81/80]
        allow_any_instance_of(Chef::ServerAPI).to receive(:post_rest).and_return(
                                                                                ^

72 files inspected, 2 offenses detected
RuboCop failed!
```

- And update the README and the tests to use Chef `11.8` instead of `11.4`. Something like the following:

```patch
diff --git a/.travis.yml b/.travis.yml
index 4be3318..a771621 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,7 +9,7 @@ rvm:
 sudo: false
 
 env:
-  - CHEF_VERSION="= 11.4.0"
+  - CHEF_VERSION="= 11.8.0"
   - CHEF_VERSION="~> 11.0"
   - CHEF_VERSION="= 12.0.0"
   - CHEF_VERSION="~> 12.0"
diff --git a/README.md b/README.md
index b487a82..30b66f5 100644
--- a/README.md
+++ b/README.md
@@ -19,7 +19,7 @@ Node attributes are encrypted using chef client and user keys with public key in
 ## Requirements
 
 * Ruby `>= 1.9`
-* Chef Client `~> 11.4`
+* Chef Client `~> 11.8`
 * yajl_ruby `~> 1.1` or ffi_yajl `>= 1.0, <3.0` (included with Chef)
 * If you want to use protocol version 2 to use [GCM](http://en.wikipedia.org/wiki/Galois/Counter_Mode) (disabled by default):
  * Ruby `>= 2`.
diff --git a/chef-encrypted-attributes.gemspec b/chef-encrypted-attributes.gemspec
index c2ee484..f86dd36 100644
--- a/chef-encrypted-attributes.gemspec
+++ b/chef-encrypted-attributes.gemspec
@@ -10,7 +10,7 @@ chef_version =
   if ENV.key?('CHEF_VERSION')
     ENV['CHEF_VERSION']
   else
-    ['>= 11.4', '< 13']
+    ['>= 11.8', '< 13']
   end
 
 Gem::Specification.new do |s|
@@ -44,7 +44,7 @@ Gem::Specification.new do |s|
   end
 
   s.add_development_dependency 'rake', '~> 10.0'
-  s.add_development_dependency 'chef-zero', '~> 3.2'
+  s.add_development_dependency 'rack', '~> 1.0' if RUBY_VERSION < '2.2.2'
   s.add_development_dependency 'rspec-core', '~> 3.1'
   s.add_development_dependency 'rspec-expectations', '~> 3.1'
   s.add_development_dependency 'rspec-mocks', '~> 3.1'
```

**Comment by zuazo** [comment]
The unit tests seem broken now:

```
  1) Chef::Knife::EncryptedAttributeShow When the Chef server is ready to rock! shows the encrypted attribute
     Failure/Error: resp = rest.post_rest(escaped_query, generate_partial_search_keys(keys))
     
     NoMethodError:
       undefined method `post_rest' for #<Chef::ServerAPI:0x0000000286fb80>
     # ./lib/chef/encrypted_attribute/search_helper.rb:380:in `partial_search'
     # ./lib/chef/encrypted_attribute/search_helper.rb:180:in `block in search_by_name'
     # ./lib/chef/encrypted_attribute/search_helper.rb:129:in `call'
     # ./lib/chef/encrypted_attribute/search_helper.rb:129:in `catch_search_exceptions'
     # ./lib/chef/encrypted_attribute/search_helper.rb:179:in `search_by_name'
     # ./lib/chef/encrypted_attribute/remote_node.rb:80:in `load_attribute'
     # ./lib/chef/encrypted_attribute/api.rb:506:in `exist_on_node?'
     # ./lib/chef/knife/core/encrypted_attribute_base.rb:61:in `assert_attribute_exists'
     # ./lib/chef/knife/encrypted_attribute_show.rb:38:in `assert_valid_args'
     # ./lib/chef/knife/core/encrypted_attribute_base.rb:94:in `parse_args'
     # ./lib/chef/knife/encrypted_attribute_show.rb:53:in `run'
     # ./spec/integration/knife/encrypted_attribute_show.rb:52:in `block (3 levels) in <top (required)>'
[...]
```

Could you fix them?

See the full output [here](https://travis-ci.org/zuazo/chef-encrypted-attributes/jobs/151876689).

**Comment by zuazo** [comment]
@e100 Thank you, man. You have done awesome work here.

Do not worry about the other test errors. I need to fix some requirements in the Gemfile, but I think those errors fall outside the scope of this issue.

Give me a couple of days before reviewing and merging this.

**Comment by e100** [comment]
Is there any reason to support 1.9.2 and 1.9.3?

I can fix the gemspec for 2.0

**Comment by zuazo** [comment]
Yes, you are right: Dropping Ruby < 2 support is the way to go. They surpassed their EOL long ago anyway.

**Comment by zuazo** [comment]
Fix released in [`0.9.0`](https://github.com/zuazo/chef-encrypted-attributes/releases/tag/0.9.0).

Thanks for your contribution!!

**Pull request merged**
